name: expense_tracker
description: A Flutter expense tracking application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  http: ^0.13.5
  intl: ^0.18.1
  month_picker_dialog: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.4.4

flutter:
  uses-material-design: true